In [5]:
import numpy as np
row1= int(input("Enter the number of rows:"))
column1= int(input("Enter the number of columns:"))
matrix1= []
print("Enter the entries rowwise:")
  
# For user input
for i in range(row1):          # A for loop for row entries
    a =[]
    for j in range(column1):      # A for loop for column entries
         a.append(int(input()))
    matrix1.append(a)
row2= int(input("Enter the number of rows:"))
column2= int(input("Enter the number of columns:"))
matrix2= []
print("Enter the entries rowwise:")
  
# For user input
for i in range(row2):          # A for loop for row entries
    b=[]
    for j in range(column2):      # A for loop for column entries
         b.append(int(input()))
    matrix2.append(b)
print("First matrix:")
print(np.matrix(matrix1))
print("Second matrix:")
print(np.matrix(matrix2))   

dot_product=np.dot(matrix1,matrix2)
print("Dot product is:")
print(dot_product)

transpose1=np.transpose(matrix1)
print("Transpose of first matrix:")
print(transpose1)
print("Transpose of second matrix:")
transpose2=np.transpose(matrix2)
print(transpose2)

trace1=np.trace(matrix1)
print("Trace of first matrix:")
print(trace1)
trace2=np.trace(matrix2)
print("Trace of second matrix:")
print(trace2)

rank1=np.linalg.matrix_rank(matrix1)
print("Rank of first matrix:")
print(rank1)
rank2=np.linalg.matrix_rank(matrix2)
print("Rank of second matrix:")
print(rank2)

det1=np.linalg.det(matrix1)
print("Determinant of first matrix:")
print(det1)
det2=np.linalg.det(matrix2)
print("Determinant of second matrix:")
print(det2)
if(det1==0):
     print("Inverse for first matrix not exists, since determinant is zero:")
else:
    inv1=np.linalg.inv(matrix1)
    print("Inverse of first matrix:")
    print(inv1)
if(det2==0):
     print("Inverse for second matrix not exists, since determinant is zero:")
else:
    inv2=np.linalg.inv(matrix2)
    print("Inverse of second matrix:")
    print(inv2)
eigenvalue1,eigenvector1=np.linalg.eig(matrix1)
print("Eigen values of first matrix")
print(eigenvalue1)
print("Eigen vectors of first matrix")
print(eigenvector1)
eigenvalue2,eigenvector2=np.linalg.eig(matrix2)
print("Eigen values of second matrix")
print(eigenvalue2)
print("Eigen vectors of second matrix")
print(eigenvector2)

Enter the number of rows:2
Enter the number of columns:2
Enter the entries rowwise:
0
0
1
2
Enter the number of rows:2
Enter the number of columns:2
Enter the entries rowwise:
4
5
6
7
First matrix:
[[0 0]
 [1 2]]
Second matrix:
[[4 5]
 [6 7]]
Dot product is:
[[ 0  0]
 [16 19]]
Transpose of first matrix:
[[0 1]
 [0 2]]
Transpose of second matrix:
[[4 6]
 [5 7]]
Trace of first matrix:
2
Trace of second matrix:
11
Rank of first matrix:
1
Rank of second matrix:
2
Determinant of first matrix:
0.0
Determinant of second matrix:
-2.0000000000000013
Inverse for first matrix not exists, since determinant is zero:
Inverse of second matrix:
[[-3.5  2.5]
 [ 3.  -2. ]]
Eigen values of first matrix
[2. 0.]
Eigen vectors of first matrix
[[ 0.          0.89442719]
 [ 1.         -0.4472136 ]]
Eigen values of second matrix
[-0.17890835 11.17890835]
Eigen vectors of second matrix
[[-0.76729658 -0.57152478]
 [ 0.64129241 -0.82058481]]
