In [4]:
#Exercise 1
#1
import numpy as np
x=np.array([2,7])
y=np.array([3,7])
print("Original numbers")
print(x)
print(y)
print("Greater element")
print(np.greater(x,y))
print("Greater or equal to element")
print(np.greater_equal(x,y))
print("Lesser element")
print(np.less(x,y))
print("Lesser or equal to element")
print(np.less_equal(x,y))

Original numbers
[2 7]
[3 7]
Greater element
[False False]
Greater or equal to element
[False  True]
Lesser element
[ True False]
Lesser or equal to element
[ True  True]


In [6]:
#2
import numpy as np
print("Array of all even integers from 30 to 70")
x=np.arange(30,71,2)
print(x)

Array of all even integers from 30 to 70
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [22]:
#3
import numpy as np
print("3*3 identity matrix is")
x=np.identity(3)
print(x)

3*3 identity matrix is
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
#4
import numpy as np
x=np.arange(21)
print("original vector")
print(x)
print("After changing the sign of numbers from 9 to 15")
x[(x>=9) & (x<=15)]*=-1
print(x)

original vector
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
After changing the sign of numbers from 9 to 15
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [23]:
#5
import numpy as np
print("5 * 5 matrix with main diagonal elements 1 2 3 4 5")
x=np.diag([1,2,3,4,5])
print(x)


5 * 5 matrix with main diagonal elements 1 2 3 4 5
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [25]:
#6
import numpy as np
x=np.array([[1,2],[4,5]])
print("Original array")
print(x)
print("Sum of all elements")
print(np.sum(x))
print("Sum of elements in each column")
print(np.sum(x,axis=0))
print("Sum of elements in each row")
print(np.sum(x,axis=1))

Original array
[[1 2]
 [4 5]]
Sum of all elements
12
Sum of elements in a column
[5 7]
Sum of elements in a row
[3 9]


In [15]:
#7
import numpy as np
import os
x = np.arange(12).reshape(4, 3)
print("Original array:")
print(x)
header = 'col1 col2 col3'
np.savetxt('temp.txt', x, fmt="%d", header=header) 
print("After loading, content of the text file:")
result = np.loadtxt('temp.txt')
print(result)

Original array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
After loading, content of the text file:
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


In [28]:
#8
import numpy as np
print("First array:")
x= np.array([[1, 2], [3, 4]])
print(x)
print("Second array:")
y= np.array([[1, 2], [3, 4]])
print(y)
print("Checking two arrays are equal or not")
comparison = x == y
equal_arrays = comparison.all()

print(equal_arrays)


First array:
[[1 2]
 [3 4]]
Second array:
[[1 2]
 [3 4]]
Checking two arrays are equal or not
True


In [18]:
#9
import numpy as np 
nums = np.arange(16, dtype='int').reshape(-1, 4)
print("Original array:")
print(nums)
print("\nNew array after swapping first and last rows of the said array:")
new_nums = nums[::-1]
print(new_nums)


Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

New array after swapping first and last rows of the said array:
[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [21]:
#10
import numpy as np
x=np.array([[2,3,5],[6,8,10],[0,12,10]])
y=np.array([[1,2,8],[5,8,12],[6,20,15]])
print("First array:")
print(x)
print("Second array")
print(y)
print("Array after multipication")
print(np.multiply(x,y))

first array:
[[ 2  3  5]
 [ 6  8 10]
 [ 0 12 10]]
Second array
[[ 1  2  8]
 [ 5  8 12]
 [ 6 20 15]]
Array after multipication
[[  2   6  40]
 [ 30  64 120]
 [  0 240 150]]
